"""only date

Revision ID: 095a54cc6d0d
Revises: f57452ac6940
Create Date: 2023-04-12 14:42:42.086836

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '095a54cc6d0d'
down_revision = 'f57452ac6940'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.VARCHAR(),
               type_=sa.Date(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.Date(),
               type_=sa.VARCHAR(),
               existing_nullable=True)

    # ### end Alembic commands ###
